_target_: src.models.AdaFlow.AdaFlow

#num_api: 1579
num_api: 23469
num_mashups: 7668
feat_size: 256
lr: 0.01
weight_decay: 0.0001
frozen_api_embeds: true
#edge_rm_threhold: 0.2
update_after_test: true
top_k: 5
#save_path: ./data/gptcheck/AdaFlow/DS2/glove/
#metric_path: ./data/metric/P5/DS2/AdaFlow/glove/
seed: 12345