_target_: src.models.DySR.DySR

mashup_embeds_path: ${data_dir}/mashup_dev_embeds.npz
api_embeds_path: ${data_dir}/api_dev_embeds.npz
negative_sample: 5
api_out_channels: 128
mashup_out_channels: 128
heads: 1
edge_dropout: 1
lr: 0.002
weight_decay: 1e-4
top_k: 5
api_graph: true
api_graph_agg: mean
constrain_agg: max
constrain_heads: null
order: descending
penate_align: true
semantic_path: ${data_dir}/whole
gnn_layers: 1
dropout_test: 0.0
update_test: true
edge_message: false
edge_message_agg: mean
fix_api_embed: ture
#save_path: ./data/gptcheck/DySR/DS1/glove/
#metric_path: ./data/metric/P5/DS2/DySR/glove/
seed: 12346
